adminapp/urls.py
from django.urls import path, include
from adminapp import views as adminapp

app_name = 'adminapp'


urlpatterns = [
    path('users/', adminapp.UsersListView.as_view(), name='users'),
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>', adminapp.user_delete, name='user_delete'),

    path('categories/', adminapp.categories, name='categories'),
    path('categories/create', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/<int:pk>/', adminapp.products, name='products'),
    path('products/create/<int:pk>', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read')
]

authapp/urls.py
from django.urls import path
from authapp import views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register')
]

basketapp/urls.py
from django.urls import path, include
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='basket'),
    path('add/<int:pk>/', basketapp.basket_add, name='basket_add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='basket_remove'),
    path('edit/<int:pk>/<quantity>/', basketapp.basket_edit, name='basket_edit')
]

geekshop_server2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, include
from mainapp import views as mainapp

app_name = 'products'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('<int:pk>/<int:page>/', mainapp.products, name='product_paginate'),
    path('product/<int:pk>/', mainapp.product, name='product')
]

mainapp/models.py
from django.db import models
# from phonenumber_field.modelfields import PhoneNumberField
# говорят хорошая библеотка,но не хочется сильно париться
# verbose_name  нужен для того, чтобы наши названия подтянулись в админку

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name='Название')
    image = models.ImageField(upload_to='products/', blank=True)
    short_desc = models.CharField(max_length=255, blank=True)
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена', default=0)
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

mainapp/views.py
import json
import random

from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory

def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    return []


def get_hot_product():
    products_list = Product.objects.all()

    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    same_products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)
    return same_products_list[:3]


def index(request):
    products_list = Product.objects.all()[:4]
    print(products_list.query)
    context = {
        'products': products_list,
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    with open(f'{settings.BASE_DIR}/contacts.json') as contacts_file:
        context = {
            'contacts': json.load(contacts_file),
            'basket': get_basket(request.user)
        }
    return render(request, 'mainapp/contact.html', context)


def products(request, pk=None, page=1):
    links_menu = ProductCategory.objects.all()

    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {'name': 'Все', 'pk': 0}
        else:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)

        # page = request.GET.get('page', 1)
        paginator = Paginator(products_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'links_menu': links_menu,
            'products': products_paginator,
            'category': category_item,
            'basket': get_basket(request.user)
        }
        return render(request, 'mainapp/products_list.html', context)

    hot_product = get_hot_product()
    context = {
        'links_menu': links_menu,
        'title': 'Товары',
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/products.html', context)


def product(request, pk):
    links_menu = ProductCategory.objects.all()
    context = {
        'links_menu': links_menu,
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}"
           class={% if request.resolver_match.url_name == 'index' %}active{% endif %}>домой</a></li>
    <li><a href="{% url 'products:products' %}"
           class={% if request.resolver_match.namespace == 'products' %}active{% endif %}>продукты</a></li>
    <li><a href="{% url 'contact' %}"
           class={% if request.resolver_match.url_name == 'contacts' %}active{% endif %}>контакты</a></li>
        {% if user.is_authenticated %}
            {% if user.is_superuser %}
                <li><a href="{% url 'adminapp:users' %}">Админка</a></li>
            {% endif %}
            <li>
                <a href="{% url 'authapp:edit' %}">
                {% if user.first_name %}{{ user.first_name }}
                {% else %}Пользователь{% endif %}</a>
            </li>
            <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'authapp:register' %}">Регистрация</a></li>
            <li><a href="{% url 'authapp:login' %}">Войти</a></li>
        {% endif %}
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basketapp:basket' %}" class="basket">
    <span>
        {% if basket %}
            {{ basket.0.total_cost|floatformat:0 }} руб.<br>
            ({{ basket.0.total_quantity }} шт)
        {% endif %}
    </span>
</a>

mainapp/templates/mainapp/includes/inc_products_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:category' 0 %}"
                   class={% if request.resolver_match.url_name == 'products'%}
                            active
                         {% endif %}>Все
        </a></li>
        {% for item in links_menu %}
            <li><a href="{% url 'products:category' item.pk %}"
                   class={% if request.resolver_match.kwargs.pk == item.pk %}
                            active
                         {% endif %}>{{ item.name }}
                </a></li>
        {% endfor %}
    </ul>
</div>